
CREATE TABLE Countries (
  country_id int NOT NULL,
  code char(2) NOT NULL ,
  name varchar(64) NOT NULL ,
  full_name varchar(128) NOT NULL,
  iso3 char(3) NOT NULL ,
  number char(3)  NOT NULL ,
  continent_code int NOT NULL,
  display_order int NOT NULL DEFAULT '900' ,
) ;

-- ----------------------------
-- Records of countries / DEFAULT '900'
-- ----------------------------
INSERT INTO countries VALUES ('1', 'AD', 'Andorra', 'Principality of Andorra', 'AND', '020', 4, '7');
INSERT INTO countries VALUES ('2', 'AE', 'United Arab Emirates', 'United Arab Emirates', 'ARE', '784', 3, '232');
INSERT INTO countries VALUES ('3', 'AF', 'Afghanistan', 'Islamic Republic of Afghanistan', 'AFG', '004', 3, '3');
INSERT INTO countries VALUES ('4', 'AG', 'Antigua and Barbuda', 'Antigua and Barbuda', 'ATG', '028', 5, '11');
INSERT INTO countries VALUES ('5', 'AI', 'Anguilla', 'Anguilla', 'AIA', '660', 5, '9');
INSERT INTO countries VALUES ('6', 'AL', 'Albania', 'Republic of Albania', 'ALB', '008', 4, '4');
INSERT INTO countries VALUES ('7', 'AM', 'Armenia', 'Republic of Armenia', 'ARM', '051', 3, '13');
INSERT INTO countries VALUES ('8', 'AN', 'Netherlands Antilles', 'Netherlands Antilles', 'ANT', '530', 5, '157');
INSERT INTO countries VALUES ('9', 'AO', 'Angola', 'Republic of Angola', 'AGO', '024', 1, '8');
INSERT INTO countries VALUES ('10', 'AQ', 'Antarctica', 'Antarctica (the territory South of 60 deg S)', 'ATA', '010', 2, '10');
INSERT INTO countries VALUES ('11', 'AR', 'Argentina', 'Argentine Republic', 'ARG', '032', 7, '12');
INSERT INTO countries VALUES ('12', 'AS', 'American Samoa', 'American Samoa', 'ASM', '016', 6, '6');
INSERT INTO countries VALUES ('13', 'AT', 'Austria', 'Republic of Austria', 'AUT', '040', 4, '16');
INSERT INTO countries VALUES ('14', 'AU', 'Australia', 'Commonwealth of Australia', 'AUS', '036', 6, '15');
INSERT INTO countries VALUES ('15', 'AW', 'Aruba', 'Aruba', 'ABW', '533', 5, '14');
INSERT INTO countries VALUES ('16', 'AX', 'Åland', 'Åland Islands', 'ALA', '248', 4, '246');
INSERT INTO countries VALUES ('17', 'AZ', 'Azerbaijan', 'Republic of Azerbaijan', 'AZE', '031', 3, '17');
INSERT INTO countries VALUES ('18', 'BA', 'Bosnia and Herzegovina', 'Bosnia and Herzegovina', 'BIH', '070', 4, '29');
INSERT INTO countries VALUES ('19', 'BB', 'Barbados', 'Barbados', 'BRB', '052', 5, '21');
INSERT INTO countries VALUES ('20', 'BD', 'Bangladesh', 'Peoples Republic of Bangladesh', 'BGD', '050', 3, '20');
INSERT INTO countries VALUES ('21', 'BE', 'Belgium', 'Kingdom of Belgium', 'BEL', '056', 4, '23');
INSERT INTO countries VALUES ('22', 'BF', 'Burkina Faso', 'Burkina Faso', 'BFA', '854', 1, '37');
INSERT INTO countries VALUES ('23', 'BG', 'Bulgaria', 'Republic of Bulgaria', 'BGR', '100', 4, '36');
INSERT INTO countries VALUES ('24', 'BH', 'Bahrain', 'Kingdom of Bahrain', 'BHR', '048', 3, '19');
INSERT INTO countries VALUES ('25', 'BI', 'Burundi', 'Republic of Burundi', 'BDI', '108', 1, '38');
INSERT INTO countries VALUES ('26', 'BJ', 'Benin', 'Republic of Benin', 'BEN', '204', 1, '25');
INSERT INTO countries VALUES ('27', 'BL', 'Saint Barthélemy', 'Saint Barthelemy', 'BLM', '652', 5, '185');
INSERT INTO countries VALUES ('28', 'BM', 'Bermuda', 'Bermuda', 'BMU', '060', 5, '26');
INSERT INTO countries VALUES ('29', 'BN', 'Brunei Darussalam', 'Brunei Darussalam', 'BRN', '096', 3, '35');
INSERT INTO countries VALUES ('30', 'BO', 'Bolivia', 'Republic of Bolivia', 'BOL', '068', 7, '28');
INSERT INTO countries VALUES ('31', 'BR', 'Brazil', 'Federative Republic of Brazil', 'BRA', '076', 7, '32');
INSERT INTO countries VALUES ('32', 'BS', 'Bahamas', 'Commonwealth of the Bahamas', 'BHS', '044', 5, '18');
INSERT INTO countries VALUES ('33', 'BT', 'Bhutan', 'Kingdom of Bhutan', 'BTN', '064', 3, '27');
INSERT INTO countries VALUES ('34', 'BV', 'Bouvet Island', 'Bouvet Island (Bouvetoya)', 'BVT', '074', 2, '31');
INSERT INTO countries VALUES ('35', 'BW', 'Botswana', 'Republic of Botswana', 'BWA', '072', 1, '30');
INSERT INTO countries VALUES ('36', 'BY', 'Belarus', 'Republic of Belarus', 'BLR', '112', 4, '22');
INSERT INTO countries VALUES ('37', 'BZ', 'Belize', 'Belize', 'BLZ', '084', 5, '24');
INSERT INTO countries VALUES ('38', 'CA', 'Canada', 'Canada', 'CAN', '124', 5, '2');
INSERT INTO countries VALUES ('39', 'CC', 'Cocos (Keeling) Islands', 'Cocos (Keeling) Islands', 'CCK', '166', 3, '48');
INSERT INTO countries VALUES ('40', 'CD', 'Congo (Kinshasa)', 'Democratic Republic of the Congo', 'COD', '180', 1, '51');
INSERT INTO countries VALUES ('41', 'CF', 'Central African Republic', 'Central African Republic', 'CAF', '140', 1, '43');
INSERT INTO countries VALUES ('42', 'CG', 'Congo (Brazzaville)', 'Republic of the Congo', 'COG', '178', 1, '52');
INSERT INTO countries VALUES ('43', 'CH', 'Switzerland', 'Swiss Confederation', 'CHE', '756', 4, '214');
INSERT INTO countries VALUES ('44', 'CI', 'Côte dIvoire', 'Republic of Cote dIvoire', 'CIV', '384', 1, '55');
INSERT INTO countries VALUES ('45', 'CK', 'Cook Islands', 'Cook Islands', 'COK', '184', 6, '53');
INSERT INTO countries VALUES ('46', 'CL', 'Chile', 'Republic of Chile', 'CHL', '152', 7, '45');
INSERT INTO countries VALUES ('47', 'CM', 'Cameroon', 'Republic of Cameroon', 'CMR', '120', 1, '40');
INSERT INTO countries VALUES ('48', 'CN', 'China', 'Peoples Republic of China', 'CHN', '156', 3, '46');
INSERT INTO countries VALUES ('49', 'CO', 'Colombia', 'Republic of Colombia', 'COL', '170', 7, '49');
INSERT INTO countries VALUES ('50', 'CR', 'Costa Rica', 'Republic of Costa Rica', 'CRI', '188', 5, '54');
INSERT INTO countries VALUES ('51', 'CU', 'Cuba', 'Republic of Cuba', 'CUB', '192', 5, '57');
INSERT INTO countries VALUES ('52', 'CV', 'Cape Verde', 'Republic of Cape Verde', 'CPV', '132', 1, '41');
INSERT INTO countries VALUES ('53', 'CX', 'Christmas Island', 'Christmas Island', 'CXR', '162', 3, '47');
INSERT INTO countries VALUES ('54', 'CY', 'Cyprus', 'Republic of Cyprus', 'CYP', '196', 3, '58');
INSERT INTO countries VALUES ('55', 'CZ', 'Czech Republic', 'Czech Republic', 'CZE', '203', 4, '59');
INSERT INTO countries VALUES ('56', 'DE', 'Germany', 'Federal Republic of Germany', 'DEU', '276', 4, '82');
INSERT INTO countries VALUES ('57', 'DJ', 'Djibouti', 'Republic of Djibouti', 'DJI', '262', 1, '61');
INSERT INTO countries VALUES ('58', 'DK', 'Denmark', 'Kingdom of Denmark', 'DNK', '208', 4, '60');
INSERT INTO countries VALUES ('59', 'DM', 'Dominica', 'Commonwealth of Dominica', 'DMA', '212', 5, '62');
INSERT INTO countries VALUES ('60', 'DO', 'Dominican Republic', 'Dominican Republic', 'DOM', '214', 5, '63');
INSERT INTO countries VALUES ('61', 'DZ', 'Algeria', 'Peoples Democratic Republic of Algeria', 'DZA', '012', 1, '5');
INSERT INTO countries VALUES ('62', 'EC', 'Ecuador', 'Republic of Ecuador', 'ECU', '218', 7, '64');
INSERT INTO countries VALUES ('63', 'EE', 'Estonia', 'Republic of Estonia', 'EST', '233', 4, '69');
INSERT INTO countries VALUES ('64', 'EG', 'Egypt', 'Arab Republic of Egypt', 'EGY', '818', 1, '65');
INSERT INTO countries VALUES ('65', 'EH', 'Western Sahara', 'Western Sahara', 'ESH', '732', 1, '242');
INSERT INTO countries VALUES ('66', 'ER', 'Eritrea', 'State of Eritrea', 'ERI', '232', 1, '68');
INSERT INTO countries VALUES ('67', 'ES', 'Spain', 'Kingdom of Spain', 'ESP', '724', 4, '207');
INSERT INTO countries VALUES ('68', 'ET', 'Ethiopia', 'Federal Democratic Republic of Ethiopia', 'ETH', '231', 1, '70');
INSERT INTO countries VALUES ('69', 'FI', 'Finland', 'Republic of Finland', 'FIN', '246', 4, '74');
INSERT INTO countries VALUES ('70', 'FJ', 'Fiji', 'Republic of the Fiji Islands', 'FJI', '242', 6, '73');
INSERT INTO countries VALUES ('71', 'FK', 'Falkland Islands', 'Falkland Islands (Malvinas)', 'FLK', '238', 7, '71');
INSERT INTO countries VALUES ('72', 'FM', 'Micronesia', 'Federated States of Micronesia', 'FSM', '583', 6, '144');
INSERT INTO countries VALUES ('73', 'FO', 'Faroe Islands', 'Faroe Islands', 'FRO', '234', 4, '72');
INSERT INTO countries VALUES ('74', 'FR', 'France', 'French Republic', 'FRA', '250', 4, '75');
INSERT INTO countries VALUES ('75', 'GA', 'Gabon', 'Gabonese Republic', 'GAB', '266', 1, '79');
INSERT INTO countries VALUES ('76', 'GB', 'United Kingdom', 'United Kingdom of Great Britain & Northern Ireland', 'GBR', '826', 4, '233');
INSERT INTO countries VALUES ('77', 'GD', 'Grenada', 'Grenada', 'GRD', '308', 5, '87');
INSERT INTO countries VALUES ('78', 'GE', 'Georgia', 'Georgia', 'GEO', '268', 3, '81');
INSERT INTO countries VALUES ('79', 'GF', 'French Guiana', 'French Guiana', 'GUF', '254', 7, '76');
INSERT INTO countries VALUES ('80', 'GG', 'Guernsey', 'Bailiwick of Guernsey', 'GGY', '831', 4, '91');
INSERT INTO countries VALUES ('81', 'GH', 'Ghana', 'Republic of Ghana', 'GHA', '288', 1, '83');
INSERT INTO countries VALUES ('82', 'GI', 'Gibraltar', 'Gibraltar', 'GIB', '292', 4, '84');
INSERT INTO countries VALUES ('83', 'GL', 'Greenland', 'Greenland', 'GRL', '304', 5, '86');
INSERT INTO countries VALUES ('84', 'GM', 'Gambia', 'Republic of the Gambia', 'GMB', '270', 1, '80');
INSERT INTO countries VALUES ('85', 'GN', 'Guinea', 'Republic of Guinea', 'GIN', '324', 1, '92');
INSERT INTO countries VALUES ('86', 'GP', 'Guadeloupe', 'Guadeloupe', 'GLP', '312', 5, '88');
INSERT INTO countries VALUES ('87', 'GQ', 'Equatorial Guinea', 'Republic of Equatorial Guinea', 'GNQ', '226', 1, '67');
INSERT INTO countries VALUES ('88', 'GR', 'Greece', 'Hellenic Republic Greece', 'GRC', '300', 4, '85');
INSERT INTO countries VALUES ('89', 'GS', 'South Georgia and South Sandwich Islands', 'South Georgia and the South Sandwich Islands', 'SGS', '239', 2, '206');
INSERT INTO countries VALUES ('90', 'GT', 'Guatemala', 'Republic of Guatemala', 'GTM', '320', 5, '90');
INSERT INTO countries VALUES ('91', 'GU', 'Guam', 'Guam', 'GUM', '316', 6, '89');
INSERT INTO countries VALUES ('92', 'GW', 'Guinea-Bissau', 'Republic of Guinea-Bissau', 'GNB', '624', 1, '93');
INSERT INTO countries VALUES ('93', 'GY', 'Guyana', 'Co-operative Republic of Guyana', 'GUY', '328', 7, '94');
INSERT INTO countries VALUES ('94', 'HK', 'Hong Kong', 'Hong Kong Special Administrative Region of China', 'HKG', '344', 3, '99');
INSERT INTO countries VALUES ('95', 'HM', 'Heard and McDonald Islands', 'Heard Island and McDonald Islands', 'HMD', '334', 2, '96');
INSERT INTO countries VALUES ('96', 'HN', 'Honduras', 'Republic of Honduras', 'HND', '340', 5, '98');
INSERT INTO countries VALUES ('97', 'HR', 'Croatia', 'Republic of Croatia', 'HRV', '191', 4, '56');
INSERT INTO countries VALUES ('98', 'HT', 'Haiti', 'Republic of Haiti', 'HTI', '332', 5, '95');
INSERT INTO countries VALUES ('99', 'HU', 'Hungary', 'Republic of Hungary', 'HUN', '348', 4, '100');
INSERT INTO countries VALUES ('100', 'ID', 'Indonesia', 'Republic of Indonesia', 'IDN', '360', 3, '103');
INSERT INTO countries VALUES ('101', 'IE', 'Ireland', 'Ireland', 'IRL', '372', 4, '106');
INSERT INTO countries VALUES ('102', 'IL', 'Israel', 'State of Israel', 'ISR', '376', 3, '108');
INSERT INTO countries VALUES ('103', 'IM', 'Isle of Man', 'Isle of Man', 'IMN', '833', 4, '107');
INSERT INTO countries VALUES ('104', 'IN', 'India', 'Republic of India', 'IND', '356', 3, '102');
INSERT INTO countries VALUES ('105', 'IO', 'British Indian Ocean Territory', 'British Indian Ocean Territory (Chagos Archipelago)', 'IOT', '086', 3, '33');
INSERT INTO countries VALUES ('106', 'IQ', 'Iraq', 'Republic of Iraq', 'IRQ', '368', 3, '105');
INSERT INTO countries VALUES ('107', 'IR', 'Iran', 'Islamic Republic of Iran', 'IRN', '364', 3, '104');
INSERT INTO countries VALUES ('108', 'IS', 'Iceland', 'Republic of Iceland', 'ISL', '352', 4, '101');
INSERT INTO countries VALUES ('109', 'IT', 'Italy', 'Italian Republic', 'ITA', '380', 4, '109');
INSERT INTO countries VALUES ('110', 'JE', 'Jersey', 'Bailiwick of Jersey', 'JEY', '832', 4, '112');
INSERT INTO countries VALUES ('111', 'JM', 'Jamaica', 'Jamaica', 'JAM', '388', 5, '110');
INSERT INTO countries VALUES ('112', 'JO', 'Jordan', 'Hashemite Kingdom of Jordan', 'JOR', '400', 3, '113');
INSERT INTO countries VALUES ('113', 'JP', 'Japan', 'Japan', 'JPN', '392', 3, '111');
INSERT INTO countries VALUES ('114', 'KE', 'Kenya', 'Republic of Kenya', 'KEN', '404', 1, '115');
INSERT INTO countries VALUES ('115', 'KG', 'Kyrgyzstan', 'Kyrgyz Republic', 'KGZ', '417', 3, '120');
INSERT INTO countries VALUES ('116', 'KH', 'Cambodia', 'Kingdom of Cambodia', 'KHM', '116', 3, '39');
INSERT INTO countries VALUES ('117', 'KI', 'Kiribati', 'Republic of Kiribati', 'KIR', '296', 6, '116');
INSERT INTO countries VALUES ('118', 'KM', 'Comoros', 'Union of the Comoros', 'COM', '174', 1, '50');
INSERT INTO countries VALUES ('119', 'KN', 'Saint Kitts and Nevis', 'Federation of Saint Kitts and Nevis', 'KNA', '659', 5, '187');
INSERT INTO countries VALUES ('120', 'KP', 'Korea, North', 'Democratic Peoples Republic of Korea', 'PRK', '408', 3, '117');
INSERT INTO countries VALUES ('121', 'KR', 'Korea, South', 'Republic of Korea', 'KOR', '410', 3, '118');
INSERT INTO countries VALUES ('122', 'KW', 'Kuwait', 'State of Kuwait', 'KWT', '414', 3, '119');
INSERT INTO countries VALUES ('123', 'KY', 'Cayman Islands', 'Cayman Islands', 'CYM', '136', 5, '42');
INSERT INTO countries VALUES ('124', 'KZ', 'Kazakhstan', 'Republic of Kazakhstan', 'KAZ', '398', 3, '114');
INSERT INTO countries VALUES ('125', 'LA', 'Laos', 'Lao Peoples Democratic Republic', 'LAO', '418', 3, '121');
INSERT INTO countries VALUES ('126', 'LB', 'Lebanon', 'Lebanese Republic', 'LBN', '422', 3, '123');
INSERT INTO countries VALUES ('127', 'LC', 'Saint Lucia', 'Saint Lucia', 'LCA', '662', 5, '188');
INSERT INTO countries VALUES ('128', 'LI', 'Liechtenstein', 'Principality of Liechtenstein', 'LIE', '438', 4, '127');
INSERT INTO countries VALUES ('129', 'LK', 'Sri Lanka', 'Democratic Socialist Republic of Sri Lanka', 'LKA', '144', 3, '208');
INSERT INTO countries VALUES ('130', 'LR', 'Liberia', 'Republic of Liberia', 'LBR', '430', 1, '125');
INSERT INTO countries VALUES ('131', 'LS', 'Lesotho', 'Kingdom of Lesotho', 'LSO', '426', 1, '124');
INSERT INTO countries VALUES ('132', 'LT', 'Lithuania', 'Republic of Lithuania', 'LTU', '440', 4, '128');
INSERT INTO countries VALUES ('133', 'LU', 'Luxembourg', 'Grand Duchy of Luxembourg', 'LUX', '442', 4, '129');
INSERT INTO countries VALUES ('134', 'LV', 'Latvia', 'Republic of Latvia', 'LVA', '428', 4, '122');
INSERT INTO countries VALUES ('135', 'LY', 'Libya', 'Libyan Arab Jamahiriya', 'LBY', '434', 1, '126');
INSERT INTO countries VALUES ('136', 'MA', 'Morocco', 'Kingdom of Morocco', 'MAR', '504', 1, '150');
INSERT INTO countries VALUES ('137', 'MC', 'Monaco', 'Principality of Monaco', 'MCO', '492', 4, '146');
INSERT INTO countries VALUES ('138', 'MD', 'Moldova', 'Republic of Moldova', 'MDA', '498', 4, '145');
INSERT INTO countries VALUES ('139', 'ME', 'Montenegro', 'Republic of Montenegro', 'MNE', '499', 4, '148');
INSERT INTO countries VALUES ('140', 'MF', 'Saint Martin (French part)', 'Saint Martin', 'MAF', '663', 5, '189');
INSERT INTO countries VALUES ('141', 'MG', 'Madagascar', 'Republic of Madagascar', 'MDG', '450', 1, '132');
INSERT INTO countries VALUES ('142', 'MH', 'Marshall Islands', 'Republic of the Marshall Islands', 'MHL', '584', 6, '138');
INSERT INTO countries VALUES ('143', 'MK', 'Macedonia', 'Republic of Macedonia', 'MKD', '807', 4, '131');
INSERT INTO countries VALUES ('144', 'ML', 'Mali', 'Republic of Mali', 'MLI', '466', 1, '136');
INSERT INTO countries VALUES ('145', 'MM', 'Myanmar', 'Union of Myanmar', 'MMR', '104', 3, '152');
INSERT INTO countries VALUES ('146', 'MN', 'Mongolia', 'Mongolia', 'MNG', '496', 3, '147');
INSERT INTO countries VALUES ('147', 'MO', 'Macau', 'Macao Special Administrative Region of China', 'MAC', '446', 3, '130');
INSERT INTO countries VALUES ('148', 'MP', 'Northern Mariana Islands', 'Commonwealth of the Northern Mariana Islands', 'MNP', '580', 6, '165');
INSERT INTO countries VALUES ('149', 'MQ', 'Martinique', 'Martinique', 'MTQ', '474', 5, '139');
INSERT INTO countries VALUES ('150', 'MR', 'Mauritania', 'Islamic Republic of Mauritania', 'MRT', '478', 1, '140');
INSERT INTO countries VALUES ('151', 'MS', 'Montserrat', 'Montserrat', 'MSR', '500', 5, '149');
INSERT INTO countries VALUES ('152', 'MT', 'Malta', 'Republic of Malta', 'MLT', '470', 4, '137');
INSERT INTO countries VALUES ('153', 'MU', 'Mauritius', 'Republic of Mauritius', 'MUS', '480', 1, '141');
INSERT INTO countries VALUES ('154', 'MV', 'Maldives', 'Republic of Maldives', 'MDV', '462', 3, '135');
INSERT INTO countries VALUES ('155', 'MW', 'Malawi', 'Republic of Malawi', 'MWI', '454', 1, '133');
INSERT INTO countries VALUES ('156', 'MX', 'Mexico', 'United Mexican States', 'MEX', '484', 5, '143');
INSERT INTO countries VALUES ('157', 'MY', 'Malaysia', 'Malaysia', 'MYS', '458', 3, '134');
INSERT INTO countries VALUES ('158', 'MZ', 'Mozambique', 'Republic of Mozambique', 'MOZ', '508', 1, '151');
INSERT INTO countries VALUES ('159', 'NA', 'Namibia', 'Republic of Namibia', 'NAM', '516', 1, '153');
INSERT INTO countries VALUES ('160', 'NC', 'New Caledonia', 'New Caledonia', 'NCL', '540', 6, '158');
INSERT INTO countries VALUES ('161', 'NE', 'Niger', 'Republic of Niger', 'NER', '562', 1, '161');
INSERT INTO countries VALUES ('162', 'NF', 'Norfolk Island', 'Norfolk Island', 'NFK', '574', 6, '164');
INSERT INTO countries VALUES ('163', 'NG', 'Nigeria', 'Federal Republic of Nigeria', 'NGA', '566', 1, '162');
INSERT INTO countries VALUES ('164', 'NI', 'Nicaragua', 'Republic of Nicaragua', 'NIC', '558', 5, '160');
INSERT INTO countries VALUES ('165', 'NL', 'Netherlands', 'Kingdom of the Netherlands', 'NLD', '528', 4, '156');
INSERT INTO countries VALUES ('166', 'NO', 'Norway', 'Kingdom of Norway', 'NOR', '578', 4, '166');
INSERT INTO countries VALUES ('167', 'NP', 'Nepal', 'State of Nepal', 'NPL', '524', 3, '155');
INSERT INTO countries VALUES ('168', 'NR', 'Nauru', 'Republic of Nauru', 'NRU', '520', 6, '154');
INSERT INTO countries VALUES ('169', 'NU', 'Niue', 'Niue', 'NIU', '570', 6, '163');
INSERT INTO countries VALUES ('170', 'NZ', 'New Zealand', 'New Zealand', 'NZL', '554', 6, '159');
INSERT INTO countries VALUES ('171', 'OM', 'Oman', 'Sultanate of Oman', 'OMN', '512', 3, '167');
INSERT INTO countries VALUES ('172', 'PA', 'Panama', 'Republic of Panama', 'PAN', '591', 5, '171');
INSERT INTO countries VALUES ('173', 'PE', 'Peru', 'Republic of Peru', 'PER', '604', 7, '174');
INSERT INTO countries VALUES ('174', 'PF', 'French Polynesia', 'French Polynesia', 'PYF', '258', 6, '77');
INSERT INTO countries VALUES ('175', 'PG', 'Papua New Guinea', 'Independent State of Papua New Guinea', 'PNG', '598', 6, '172');
INSERT INTO countries VALUES ('176', 'PH', 'Philippines', 'Republic of the Philippines', 'PHL', '608', 3, '175');
INSERT INTO countries VALUES ('177', 'PK', 'Pakistan', 'Islamic Republic of Pakistan', 'PAK', '586', 3, '168');
INSERT INTO countries VALUES ('178', 'PL', 'Poland', 'Republic of Poland', 'POL', '616', 4, '177');
INSERT INTO countries VALUES ('179', 'PM', 'Saint Pierre and Miquelon', 'Saint Pierre and Miquelon', 'SPM', '666', 5, '190');
INSERT INTO countries VALUES ('180', 'PN', 'Pitcairn', 'Pitcairn Islands', 'PCN', '612', 6, '176');
INSERT INTO countries VALUES ('181', 'PR', 'Puerto Rico', 'Commonwealth of Puerto Rico', 'PRI', '630', 5, '179');
INSERT INTO countries VALUES ('182', 'PS', 'Palestine', 'Occupied Palestinian Territory', 'PSE', '275', 3, '170');
INSERT INTO countries VALUES ('183', 'PT', 'Portugal', 'Portuguese Republic', 'PRT', '620', 4, '178');
INSERT INTO countries VALUES ('184', 'PW', 'Palau', 'Republic of Palau', 'PLW', '585', 6, '169');
INSERT INTO countries VALUES ('185', 'PY', 'Paraguay', 'Republic of Paraguay', 'PRY', '600', 7, '173');
INSERT INTO countries VALUES ('186', 'QA', 'Qatar', 'State of Qatar', 'QAT', '634', 3, '180');
INSERT INTO countries VALUES ('187', 'RE', 'Reunion', 'Reunion', 'REU', '638', 1, '181');
INSERT INTO countries VALUES ('188', 'RO', 'Romania', 'Romania', 'ROU', '642', 4, '182');
INSERT INTO countries VALUES ('189', 'RS', 'Serbia', 'Republic of Serbia', 'SRB', '688', 4, '197');
INSERT INTO countries VALUES ('190', 'RU', 'Russian Federation', 'Russian Federation', 'RUS', '643', 4, '183');
INSERT INTO countries VALUES ('191', 'RW', 'Rwanda', 'Republic of Rwanda', 'RWA', '646', 1, '184');
INSERT INTO countries VALUES ('192', 'SA', 'Saudi Arabia', 'Kingdom of Saudi Arabia', 'SAU', '682', 3, '195');
INSERT INTO countries VALUES ('193', 'SB', 'Solomon Islands', 'Solomon Islands', 'SLB', '090', 6, '203');
INSERT INTO countries VALUES ('194', 'SC', 'Seychelles', 'Republic of Seychelles', 'SYC', '690', 1, '198');
INSERT INTO countries VALUES ('195', 'SD', 'Sudan', 'Republic of Sudan', 'SDN', '736', 1, '209');
INSERT INTO countries VALUES ('196', 'SE', 'Sweden', 'Kingdom of Sweden', 'SWE', '752', 4, '213');
INSERT INTO countries VALUES ('197', 'SG', 'Singapore', 'Republic of Singapore', 'SGP', '702', 3, '200');
INSERT INTO countries VALUES ('198', 'SH', 'Saint Helena', 'Saint Helena', 'SHN', '654', 1, '186');
INSERT INTO countries VALUES ('199', 'SI', 'Slovenia', 'Republic of Slovenia', 'SVN', '705', 4, '202');
INSERT INTO countries VALUES ('200', 'SJ', 'Svalbard and Jan Mayen Islands', 'Svalbard & Jan Mayen Islands', 'SJM', '744', 4, '211');
INSERT INTO countries VALUES ('201', 'SK', 'Slovakia', 'Slovakia (Slovak Republic)', 'SVK', '703', 4, '201');
INSERT INTO countries VALUES ('202', 'SL', 'Sierra Leone', 'Republic of Sierra Leone', 'SLE', '694', 1, '199');
INSERT INTO countries VALUES ('203', 'SM', 'San Marino', 'Republic of San Marino', 'SMR', '674', 4, '193');
INSERT INTO countries VALUES ('204', 'SN', 'Senegal', 'Republic of Senegal', 'SEN', '686', 1, '196');
INSERT INTO countries VALUES ('205', 'SO', 'Somalia', 'Somali Republic', 'SOM', '706', 1, '204');
INSERT INTO countries VALUES ('206', 'SR', 'Suriname', 'Republic of Suriname', 'SUR', '740', 7, '210');
INSERT INTO countries VALUES ('207', 'ST', 'Sao Tome and Principe', 'Democratic Republic of Sao Tome and Principe', 'STP', '678', 1, '194');
INSERT INTO countries VALUES ('208', 'SV', 'El Salvador', 'Republic of El Salvador', 'SLV', '222', 5, '66');
INSERT INTO countries VALUES ('209', 'SY', 'Syria', 'Syrian Arab Republic', 'SYR', '760', 3, '215');
INSERT INTO countries VALUES ('210', 'SZ', 'Swaziland', 'Kingdom of Swaziland', 'SWZ', '748', 1, '212');
INSERT INTO countries VALUES ('211', 'TC', 'Turks and Caicos Islands', 'Turks and Caicos Islands', 'TCA', '796', 5, '228');
INSERT INTO countries VALUES ('212', 'TD', 'Chad', 'Republic of Chad', 'TCD', '148', 1, '44');
INSERT INTO countries VALUES ('213', 'TF', 'French Southern Lands', 'French Southern Territories', 'ATF', '260', 2, '78');
INSERT INTO countries VALUES ('214', 'TG', 'Togo', 'Togolese Republic', 'TGO', '768', 1, '221');
INSERT INTO countries VALUES ('215', 'TH', 'Thailand', 'Kingdom of Thailand', 'THA', '764', 3, '219');
INSERT INTO countries VALUES ('216', 'TJ', 'Tajikistan', 'Republic of Tajikistan', 'TJK', '762', 3, '217');
INSERT INTO countries VALUES ('217', 'TK', 'Tokelau', 'Tokelau', 'TKL', '772', 6, '222');
INSERT INTO countries VALUES ('218', 'TL', 'Timor-Leste', 'Democratic Republic of Timor-Leste', 'TLS', '626', 3, '220');
INSERT INTO countries VALUES ('219', 'TM', 'Turkmenistan', 'Turkmenistan', 'TKM', '795', 3, '227');
INSERT INTO countries VALUES ('220', 'TN', 'Tunisia', 'Tunisian Republic', 'TUN', '788', 1, '225');
INSERT INTO countries VALUES ('221', 'TO', 'Tonga', 'Kingdom of Tonga', 'TON', '776', 6, '223');
INSERT INTO countries VALUES ('222', 'TR', 'Turkey', 'Republic of Turkey', 'TUR', '792', 3, '226');
INSERT INTO countries VALUES ('223', 'TT', 'Trinidad and Tobago', 'Republic of Trinidad and Tobago', 'TTO', '780', 5, '224');
INSERT INTO countries VALUES ('224', 'TV', 'Tuvalu', 'Tuvalu', 'TUV', '798', 6, '229');
INSERT INTO countries VALUES ('225', 'TW', 'Taiwan', 'Taiwan', 'TWN', '158', 3, '216');
INSERT INTO countries VALUES ('226', 'TZ', 'Tanzania', 'United Republic of Tanzania', 'TZA', '834', 1, '218');
INSERT INTO countries VALUES ('227', 'UA', 'Ukraine', 'Ukraine', 'UKR', '804', 4, '231');
INSERT INTO countries VALUES ('228', 'UG', 'Uganda', 'Republic of Uganda', 'UGA', '800', 1, '230');
INSERT INTO countries VALUES ('229', 'UM', 'United States Minor Outlying Islands', 'United States Minor Outlying Islands', 'UMI', '581', 6, '234');
INSERT INTO countries VALUES ('230', 'US', 'United States of America', 'United States of America', 'USA', '840', 5, '1');
INSERT INTO countries VALUES ('231', 'UY', 'Uruguay', 'Eastern Republic of Uruguay', 'URY', '858', 7, '236');
INSERT INTO countries VALUES ('232', 'UZ', 'Uzbekistan', 'Republic of Uzbekistan', 'UZB', '860', 3, '237');
INSERT INTO countries VALUES ('233', 'VA', 'Vatican City', 'Holy See (Vatican City State)', 'VAT', '336', 4, '97');
INSERT INTO countries VALUES ('234', 'VC', 'Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines', 'VCT', '670', 5, '191');
INSERT INTO countries VALUES ('235', 'VE', 'Venezuela', 'Bolivarian Republic of Venezuela', 'VEN', '862', 7, '239');
INSERT INTO countries VALUES ('236', 'VG', 'Virgin Islands, British', 'British Virgin Islands', 'VGB', '092', 5, '34');
INSERT INTO countries VALUES ('237', 'VI', 'Virgin Islands, U.S.', 'United States Virgin Islands', 'VIR', '850', 5, '235');
INSERT INTO countries VALUES ('238', 'VN', 'Vietnam', 'Socialist Republic of Vietnam', 'VNM', '704', 3, '240');
INSERT INTO countries VALUES ('239', 'VU', 'Vanuatu', 'Republic of Vanuatu', 'VUT', '548', 6, '238');
INSERT INTO countries VALUES ('240', 'WF', 'Wallis and Futuna Islands', 'Wallis and Futuna', 'WLF', '876', 6, '241');
INSERT INTO countries VALUES ('241', 'WS', 'Samoa', 'Independent State of Samoa', 'WSM', '882', 6, '192');
INSERT INTO countries VALUES ('242', 'YE', 'Yemen', 'Yemen', 'YEM', '887', 3, '243');
INSERT INTO countries VALUES ('243', 'YT', 'Mayotte', 'Mayotte', 'MYT', '175', 1, '142');
INSERT INTO countries VALUES ('244', 'ZA', 'South Africa', 'Republic of South Africa', 'ZAF', '710', 1, '205');
INSERT INTO countries VALUES ('245', 'ZM', 'Zambia', 'Republic of Zambia', 'ZMB', '894', 1, '244');
INSERT INTO countries VALUES ('246', 'ZW', 'Zimbabwe', 'Republic of Zimbabwe', 'ZWE', '716', 1, '245');