USE [master]
GO
/****** Object:  Database [New]    Script Date: 11/25/2019 2:20:27 PM ******/
CREATE DATABASE [New]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'New', FILENAME = N'E:\sqlTemp\MSSQL\DATA\New.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'New_log', FILENAME = N'E:\sqlTemp\MSSQL\DATA\New_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [New] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [New].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [New] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [New] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [New] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [New] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [New] SET ARITHABORT OFF 
GO
ALTER DATABASE [New] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [New] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [New] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [New] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [New] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [New] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [New] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [New] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [New] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [New] SET  DISABLE_BROKER 
GO
ALTER DATABASE [New] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [New] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [New] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [New] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [New] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [New] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [New] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [New] SET RECOVERY FULL 
GO
ALTER DATABASE [New] SET  MULTI_USER 
GO
ALTER DATABASE [New] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [New] SET DB_CHAINING OFF 
GO
ALTER DATABASE [New] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [New] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [New] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'New', N'ON'
GO
ALTER DATABASE [New] SET QUERY_STORE = OFF
GO
USE [New]
GO
/****** Object:  Table [dbo].[EmployeeInfo]    Script Date: 11/25/2019 2:20:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EmployeeInfo](
	[EmpId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NULL,
	[Gender] [nvarchar](50) NULL,
	[City] [nvarchar](100) NULL,
 CONSTRAINT [PK_EmployeeInfo] PRIMARY KEY CLUSTERED 
(
	[EmpId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[EmployeeInfo] ON 
GO
INSERT [dbo].[EmployeeInfo] ([EmpId], [Name], [Gender], [City]) VALUES (1, N'mike', N'male', N'London')
GO
INSERT [dbo].[EmployeeInfo] ([EmpId], [Name], [Gender], [City]) VALUES (2, N'john', N'male', N'chennai')
GO
INSERT [dbo].[EmployeeInfo] ([EmpId], [Name], [Gender], [City]) VALUES (3, N'ales', N'female', N'Gothon')
GO
INSERT [dbo].[EmployeeInfo] ([EmpId], [Name], [Gender], [City]) VALUES (4, N'mikel', N'male', N'sydeny')
GO
INSERT [dbo].[EmployeeInfo] ([EmpId], [Name], [Gender], [City]) VALUES (5, N'pam', N'female', N'toronto')
GO
INSERT [dbo].[EmployeeInfo] ([EmpId], [Name], [Gender], [City]) VALUES (6, N'david', N'male', N'broklin')
GO
INSERT [dbo].[EmployeeInfo] ([EmpId], [Name], [Gender], [City]) VALUES (7, N'saad', N'male', N'istanbul')
GO
INSERT [dbo].[EmployeeInfo] ([EmpId], [Name], [Gender], [City]) VALUES (8, N'ali', N'male', N'amman')
GO
INSERT [dbo].[EmployeeInfo] ([EmpId], [Name], [Gender], [City]) VALUES (9, N'baraa', N'male', N'irbid')
GO
SET IDENTITY_INSERT [dbo].[EmployeeInfo] OFF
GO
USE [master]
GO
ALTER DATABASE [New] SET  READ_WRITE 
GO
